### PR TITLE
fix: add concrete exceptions to the adapter

### PR DESCRIPTION
**Pull request by andersmateusz**

### CODE REVIEW

**Comment by 36864** [comment]
Thanks. I've been meaning to do this for a while now. 

I will review and merge over the weekend.

**Comment by andersmateusz** [comment]
Great! Thank you for letting me know. I was doing this in hurry so I will also review this code before the weekend. One bug I've also noticed while using this adapter in my project is that `fstat` method while writting stream might return false, so I would handle this properly as well. I got `false` when reading stream from other filesystem (Azure Storage) using appropiate adapter. It seems that I have to write the stream to a new resource before writting this to Drive. I've also added some minor changes regarding code style (i.e.  type annotations, typing). You are allowed to edit this code so feel free to adjust this code as u prefer.

**Review by 36864 — APPROVED** [review]
LGTM

**Comment by 36864** [comment]
Sorry for the delay, weekend got away from me.
As for the `fstat` bug, I don't currently have any use cases for it so I haven't run into it. Will investigate when I have time, which at this pace is going to be next year.

**Comment by andersmateusz** [comment]
`fstat` bug might be related to type of resource that is generated by the other adapter. I've added exception if `false` is returned bt `fstat` in this merge request so I think this is enough

**Pull request merged**
