### PR TITLE
Use batch requests when creating directories

### PR DESCRIPTION
**Pull request by dcblogdev**
changed single upload to a batch request, this way you can create nested folders in one shot ie

Storage::disk('msgraph')->makeDirectory('demo/2/3/4/5/6');

This change also allows compatibility with Spatie media library as an added bonus.

### CODE REVIEW

**Comment by 36864** [comment]
Feels wrong to use a batch request with only one request in it. From this it looks like the only thing that would be making a difference is using `$this->getDriveRootUrl() . ":/$path:/children"` instead of `$this->getDriveItemUrl($parentItem) . '/children'`, but that breaks if you try to create a directory in the root path and indeed testing your code I can't create a new directory that is a direct child of the root directory.

Looks like there's an easy fix though, just using `$this->getUrlToPath($path) . ':/children'` seems to fix everything. I'll go ahead and push that change through and cut a new release shortly.

Thank you for bringing attention to this.

**Comment by dcblogdev** [comment]
okay great, I'll give this a try when it's released. Thanks for the quick response.

**Comment by 36864** [comment]
Should be fixed. My tests may not be perfect, so let me know if the new update breaks anything.

**Comment by dcblogdev** [comment]
brilliant, will do.

**Comment by dcblogdev** [comment]
slight problem nested folders works but when creating a single folder the response is 

```
Client error: `POST https://graph.microsoft.com/v1.0/drives/{id}/root:/children` resulted in a `400 Bad Request` response: {"error":{"code":"invalidRequest","message":"Invalid request","innerError":{"date":"2023-06-16T15:32:58","request-id":"254fb125-e950-4469-a1cf-d99229511fea","client-request-id":"254fb125-e950-4469-a1cf-d99229511fea"}}}
```

is there a way that if the folder already exists to does not attempt to create it?

The reason is Spatie's media library package when downloading files will internally call `makeDirectory` which will error out when there is a folder that already exists.

**Comment by 36864** [comment]
Microsoft supports three values for `"@microsoft.graph.conflictBehavior"`: "fail", "rename", and "replace". I can accept that as an option in the adapter constructor, but I'm not sure what would be acceptable here.
We could also accept and extra "ignore" option that would basically use `"fail" but catch the exception.
Thoughts?

**Comment by dcblogdev** [comment]
I like the sound of the ignore option if I can set this when setting up the adapter I think that will be enough

**Comment by 36864** [comment]
Looking at other flysystem adapters, they're just checking if the directory exists before creating and returning true if it does. No reason why we shouldn't be doing the same.

I'll make "ignore" the default option and allow overriding that. It'll cost one extra api request but does anyone really care about that?

**Comment by dcblogdev** [comment]
That would be perfect 🤩

**Comment by 36864** [comment]
There. 1.1.3 should be functional. Can't really have unit tests for this package so as per usual let me know if I broke anything again.

**Comment by dcblogdev** [comment]
Great will try it this evening

**Comment by dcblogdev** [comment]
all working perfectly, thanks for your help.

**Pull request closed without merging**
